version: '3.8'
services:
  backend:
    build:
      context: ./backend
    ports:
      - ${PORT_BACK}:${PORT_BACK}
    env_file: .env
    command: npm start
    networks:
      - todo

  database:
    env_file: ./.env
    image: mysql:8.0
    ports:
      - ${PORT_MYSQL}:3306
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql
      - mysql_config:/etc/mysql
    networks:
      - todo
networks:
  todo:
volumes:
  mysql:
  mysql_config: