name: Equipe Workflow

on: 
  push: 
    branches: [ "front-end" ]
  pull_request: 
    branches: [ "front-end" ]

jobs:
  
  first-job:
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: echo Ingra e Igor
