name: My first Workflow


on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - 'release*'
      - init-front-end
  workflow_dispatch:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Entrando no front-end
      run: cd frontend && ls
    - name: Run tests
      run: npm test