name: My first Workflow


on: 
  push: 
    branches: [ "segunda-lista" ]
  pull_request: 
    branches: [ "segunda-lista" ]
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run teste
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          cd backend
          npm i 
          npm run test
