name: test-workflow

on: [push]

jobs:
  test:
    name: Run tests
    runs-on: [ubuntu-18.04, ubuntu-20.04, ubuntu-22.04]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: echo "npm install"

      - name: Run tests
        run: echo "npm test"